[project]
name = "learning-python"
version = "0.1.0"
description = "Project to explore Python's possibilities"
readme = "README.md"
authors = [
    { name = "Maxime C.", email = "carlu.m@sfeir.com" }
]
requires-python = ">=3.12"
dependencies = []
classifiers = ["Private :: Do Not Upload"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
learning-python = "learning_python:main"

[tool.ruff.lint]
extend-select = ["B"]

[tool.pytest.ini_options]
addopts = "--maxfail=1 --cov=learning_python"
